import os
import re

files_and_translations = {
  r'f:\RenPyDevelopment\Projects\DoctorNeonPrototype\game\tl\english_us\game-scripts\chapters\chapter1\7-confrontation.rpy': {
    "Мы выбежали с поста охраны. Улики были у нас в руках.": "We ran out of the security post. The evidence was in our hands.",
    "Алекс крепко схватила меня за ладонь и потащила за собой по длинному, залитому закатным солнцем коридору.": "Alex grabbed my hand tightly and dragged me along a long corridor flooded with the setting sun.",
    "Давай, Неон! Не отставай! Лифты в административное крыло прямо по курсу!": "Come on, Neon! Keep up! The elevators to the administrative wing are straight ahead!",
    "Алекс... ха-ха... мы же в научном комплексе, а не на школьной перемене! Нас могут заметить!": "Alex... haha... we're in a science complex, not on school recess! We might get noticed!",
    "Я пыталась звучать строго, но не могла сдержать искренний смех. Адреналин бурлил в крови, давая такое сладкое ощущение свободы.": "I tried to sound strict, but I couldn't hold back a genuine laugh. Adrenaline was boiling in my blood, giving such a sweet sense of freedom.",
    "Впервые за долгое время я чувствовала себя... живой. Не 'ученым', не 'вороной', а просто девчонкой, которая бежит, держась за руку с лучшей подругой.": "For the first time in a long while, I felt... alive. Not a 'scientist', not a 'sheep', but just a girl running hand in hand with her best friend.",
    "Ой, да брось! Сейчас мы — спецагенты! Ха-ха, мы так уделаем этого Маркуса, что он будет до конца жизни пробирки языком мыть!": "Oh, come on! Right now we're secret agents! Haha, we'll wipe the floor with Markus so hard he'll be washing test tubes with his tongue for the rest of his life!",
    "Она звонко рассмеялась, и этот смех эхом разнесся по пустым коридорам.": "She laughed ringingly, and this laughter echoed through the empty corridors.",
    "Глядя на ее сияющее лицо, на светлые кудри, в которых путались лучи солнца, я вдруг почувствовала, как в груди разливается тепло.": "Looking at her radiant face, at her light curls tangled with sunbeams, I suddenly felt warmth spreading in my chest.",
    "Тот самый 'Шум' мира, который я так ненавидела, рядом с ней становился тихим и безопасным.": "That very 'Noise' of the world, which I hated so much, became quiet and safe next to her.",
    "Мы замедлили шаг, тяжело дыша и улыбаясь друг другу. Мы подошли к дверям главного лифта.": "We slowed our pace, breathing heavily and smiling at each other. We approached the doors of the main elevator.",
    "Алекс, уставшая, потянулась нажать кнопку вызова, случайно скользнув костяшками пальцев по моей ладони.": "Alex, tired, reached out to press the call button, accidentally brushing her knuckles against my palm.",
    "ЦК!": "ZAP!",
    "Ай! Ой, ты меня снова ударила!": "Ouch! Oh, you shocked me again!",
    "Я посмотрела на свою руку. Искры были... синими. Обычно статика желтая или белая. Но рядом с Алекс она меняла цвет.\\": "I looked at my hand. The sparks were... blue. Usually static is yellow or white. But next to Alex it changed color.",
    "Она отдернула руку, но в этот раз в её голосе не было ни капли раздражения или испуга. Вместо этого она звонко, заливисто рассмеялась.": "She pulled her hand away, but this time there wasn't a drop of irritation or fear in her voice. Instead, she let out a ringing, hearty laugh.",
    "Её смех был таким заразительным, что я не выдержала и тоже рассмеялась в ответ. Искренне, без всякой неловкости.": "Her laugh was so contagious that I couldn't help but laugh along in response. Sincerely, without any awkwardness.",
    "Ну Неон, почему это всегда происходит, только когда мы одни?!": "Oh Neon, why does this always happen only when we're alone?!",
    "Мне же никто в отделе не верит! Все думают, что я выдумываю про то, что ты — ходячий электрошокер! Ха-ха-ха!": "Nobody in the department believes me! They all think I'm making it up about you being a walking taser! Hahaha!",
    "Хах. Может, это моя защитная реакция? Чтобы ты не расслаблялась.": "Hah. Maybe it's my defense mechanism? So you don't relax.",
    "Ой, да ладно тебе! Даже здесь ты не можешь оторваться от своих научных терминов! Ты же не на лекции!": "Oh, whatever! Even here you can't tear yourself away from your scientific terms! You're not at a lecture!",
    "Она шутливо ткнула меня локтем. Мы стояли у лифта, хихикая, как две школьницы, забыв обо всех проблемах и корпоративных правилах.": "She playfully nudged me with her elbow. We stood by the elevator, giggling like two schoolgirls, forgetting all the problems and corporate rules.",
    "Глядя на ее сияющее лицо, на эти светлые кудри и теплую улыбку, я вдруг поняла, что 'Шум' мира вокруг нас полностью исчез. Рядом с ней было... идеально тихо.": "Looking at her radiant face, those bright curls, and warm smile, I suddenly realized that the 'Noise' of the world around us had completely vanished. Next to her it was... perfectly quiet.",
    "{=whisper}Знаешь, Алекс...{/whisper}": "{=whisper}You know, Alex...{/whisper}",
    "М? Что такое, гений?": "Hmm? What is it, genius?",
    "Я посмотрела на свои руки, в которых еще секунду назад плясали искры, затем подняла на неё глаза.": "I looked at my hands, where just a second ago sparks had been dancing, then raised my eyes to her.",
    "Слова давались с трудом, я не привыкла к таким откровениям. Но мне так хотелось ей это сказать. Именно сейчас.": "The words came with difficulty; I wasn't used to such revelations. But I really wanted to tell her this. Right now.",
    "Я никогда тебе этого не говорила, но...": "I've never told you this, but...",
    "Знаешь... ты мне очень напоминаешь ту девушку... из одного виде—{nw}": "You know... you really remind me of that girl... from a vide—{nw}",
    "Мелодичный звонок лифта разрезал тишину, грубо оборвав меня на полуслове.": "The melodious chime of the elevator cut through the silence, rudely interrupting me mid-sentence.",
    "Я инстинктивно перевела взгляд на разъезжающиеся металлические двери.": "I instinctively shifted my gaze to the parting metal doors.",
    "И слова застряли у меня в горле. Сердце, секунду назад бившееся от радости, рухнуло куда-то в желудок. Кровь мгновенно заледенела.": "And the words stuck in my throat. My heart, which had been beating with joy a second ago, plummeted into my stomach. My blood instantly turned to ice.",
    "Алекс, стоявшая ко мне вполоборота, еще ничего не заметила.": "Alex, standing half-turned towards me, hadn't noticed anything yet.",
    "Она искренне не понимала, почему я впала в ступор. Она мило склонила голову набок, её глаза всё ещё светились недавним смехом.": "She genuinely didn't understand why I had fallen into a stupor. She tilted her head cutely to the side, her eyes still sparkling with recent laughter.",
    "М? Какую девушку, Неон? Что с тобой?": "Hmm? What girl, Neon? What's wrong?",
    "Я не могла ответить. Я просто в ужасе смотрела в кабину лифта.": "I couldn't answer. I just stared in horror into the elevator car.",
    "Алекс, проследив за моим остекленевшим взглядом, улыбаясь, медленно повернулась к дверям.": "Alex, following my glazed over gaze, smiled and slowly turned to the doors.",
    "И её улыбка тут же испарилась.": "And her smile instantly evaporated.",
    "Кабина была не пуста.": "The car was not empty.",
    "Оттуда выходил человек, поправляя идеально завязанный галстук дорогого костюма.": "A man stepped out, adjusting a perfectly tied tie on an expensive suit.",
    "Увидев нас, он на долю секунды замер. Но тут же нацепил на лицо выражение ленивого, снисходительного превосходства.": "Seeing us, he froze for a fraction of a second. But immediately slapped an expression of lazy, condescending superiority onto his face.",
    "Это был Маркус.": "It was Marcus.",
    "Неон. Александра. Какая... трогательная процессия. Решили прогуляться перед увольнением?": "Neon. Alexandra. What a... touching procession. Decided to take a walk before you're fired?",
    "Неон не ответила. Она просто посмотрела на него. Холодным, тяжелым взглядом.": "Neon didn't answer. She just looked at him. With a cold, heavy gaze.",
    "В ее глазах не было ни сарказма, ни злости. Только ледяная решимость.": "There was neither sarcasm nor anger in her eyes. Only icy determination.",
    "Отойди с дороги, Маркус.": "Get out of the way, Marcus.",
    "Она сделала шаг вперед, намереваясь пройти мимо. Алекс последовала за ней": "She took a step forward, intending to walk past. Alex followed her.",
    "Но Маркус сделал шаг в сторону, перекрывая ей путь своим телом. Он был выше, массивнее. Он нависал над ней.": "But Marcus took a step to the side, blocking her path with his body. He was taller, more massive. He towered over her.",
    "Тише, тише. Куда спешим? К папочке директору?": "Easy, easy. Where are we rushing? To daddy director?",
    "Узнаешь. У тебя же были дела? Ну так вот, иди.": "You'll find out. Don't you have things to do? Well then, off you go.",
    "Он протянул руку и схватил Неон за плечо. Не больно, но унизительно крепко. Как хозяин, удерживающий непослушного питомца.": "He reached out and grabbed Neon's shoulder. Not painfully, but humiliatingly tight. Like an owner restraining a disobedient pet.",
    "Его пальцы сжались на ткани ее халата.": "His fingers tightened on the fabric of her lab coat.",
    "Ты думаешь, тебе там кто-то рад? После того цирка, что ты устроила?": "You think anyone is glad to see you there? After the circus you pulled?",
    "Неон застыла от этого прикосновения. Но Алекс среагировала мгновенно.": "Neon froze at the touch. But Alex reacted instantly.",
    "Алекс рывком вклинилась между ними. Она с силой ударила по руке Маркуса, сбивая его ладонь с плеча Неон, и толкнула его в грудь.": "Alex violently wedged herself between them. She struck Marcus's arm forcefully, knocking his hand off Neon's shoulder, and shoved him in the chest.",
    "В ее глазах не было страха. Только чистая, звериная защита.": "There was no fear in her eyes. Only pure, animalistic defense.",
    "Еще раз тронешь ее — я тебе пальцы переломаю, понял?": "Touch her again and I'll break your fingers, understand?",
    "Маркус отшатнулся от неожиданности. Он посмотрел на свою руку, потом на Алекс. В его взгляде появилось брезгливое удивление, будто на него лаяла дворняжка.": "Marcus staggered back in surprise. He looked at his hand, then at Alex. A look of disgusted surprise crossed his face, as if a mutt had barked at him.",
    "Неон смотрела на спину подруги. Алекс дрожала от злости, но стояла насмерть. Она была щитом.": "Neon stared at her friend's back. Alex was trembling with anger, but standing her ground. She was a shield.",
    "Ха... Бойцовая подружка? Как мило.": "Ha... A fighting girlfriend? How cute.",
    "Он отряхнул пиджак там, где его коснулась Алекс, словно стряхивая грязь.": "He brushed off his jacket where Alex had touched him, as if shaking off dirt.",
    "Слушай, архивная пыль. Сгинь. Взрослые разговаривают.": "Listen, archive dust. Scram. The adults are talking.",
    "Я сказала — отошел от нее!": "I said — step away from her!",
    "Он проигнорировал Алекс, глядя поверх ее головы прямо на Неон": "He ignored Alex, looking over her head straight at Neon.",
    "Видишь, Неон? Ты даже за себя постоять не можешь. Тебе всегда нужна нянька.": "See, Neon? You can't even stand up for yourself. You always need a nanny.",
    "Сначала опекунша... теперь эта неудачница...": "First the guardian... now this loser...",
    "Ты жалка. Вечно прячешься за чужими спинами.": "You're pathetic. Always hiding behind others' backs.",
    "{=whisper}К-как ты узнал...?{/whisper}": "{=whisper}H-how did you know...?{/whisper}",
    "Эти слова попали в цель.": "Those words hit the mark.",
    "Неон увидела, как Алекс набирает воздух, чтобы снова ответить, чтобы снова защитить ее...": "Neon saw Alex take a breath to answer him again, to defend her again...",
    "И что-то внутри Неон оборвалось.": "And something inside Neon snapped.",
    "Стыд. Стыд за то, что она слабая. За то, что Алекс приходится драться за нее.": "Shame. Shame that she was weak. That Alex had to fight for her.",
    "Она мягко, но настойчиво отодвинула Алекс в сторону.": "She gently but firmly pushed Alex aside.",
    "Ты про опекуншу? Она немного... странная. Ну впринципе, яблоко от яблони недалеко падает, да?": "You mean the guardian? She's a bit... strange. But I guess the apple doesn't fall far from the tree, right?",
    "Но я и не думал, что она тебе так дорога.": "But I had no idea she meant so much to you.",
    "Он наклонился к моему уху, и его голос стал вкрадчивым, липким, как нефть. Он говорил так, будто знал какой-то грязный секрет моей семьи.": "He leaned in to my ear, and his voice became insinuating, sticky like oil. He spoke as if he knew some dirty family secret of mine.",
    "Ты реально думаешь, что она тебя любит? Она же даже не твоя мама.": "Do you really think she loves you? She's not even your mom.",
    "Она просто... заботится о тебе, потому что ты ей нужна.": "She just... takes care of you, because she needs you.",
    "Ты же бесполезная, Неон. Ты никому не нужна.": "You're useless, Neon. Nobody needs you.",
    "{=whisper}Алекс... отойди.": "{=whisper}Alex... step away.",
    "Неон? Не слушай его, он просто...": "Neon? Don't listen to him, he's just...",
    "Я сказала... отойди.": "I said... step away.",
    "Голос Неон был тихим, но в нем звучала такая мертвая, холодная пустота, что Алекс инстинктивно отступила.": "Neon's voice was quiet, but it held such a dead, cold emptiness in it that Alex instinctively stepped back.",
    "Маркус ухмыльнулся, думая, что победил.": "Marcus smirked, thinking he had won.",
    "Кстати. Чуть не забыл. Ты, кажется, что-то потеряла утром?": "By the way. Almost forgot. Think you lost something this morning?",
    "Он сунул руку в карман брюк и достал маленькие белые наушники. Её наушники.": "He reached into his pants pocket and pulled out small white earphones. Her earphones.",
    "Они...": "They...",
    "Отдай. Отдай немедленно.": "Give them back. Give them back right now.",
    "Забавная вещица. Я послушал, пока ты спала. Какая-то заунывная классика. И это помогает тебе работать? Серьезно?": "Amusing little thing. I listened to them while you slept. Some dreary classical music. Does this really help you work? Seriously?",
    "Не трогай их! Это... это единственное, что спасает меня от шума на работе!": "Don't touch them! It's... it's the only thing that saves me from the noise at work!",
    "Неон дернулась к нему, пытаясь выхватить их, но Маркус легко поднял руку выше, как взрослый дразнит ребенка.": "Neon lunged at him, trying to snatch them, but Marcus easily lifted his arm higher, like an adult teasing a child.",
    "Спасает от шума? Лечит душу?": "Saves you from the noise? Heals your soul?",
    "Знаешь, Неон... Я уже нашел твой сигнал. Я сделал твою работу за тебя... А значит...": "You know, Neon... I already found your signal. I did your job for you... And that means...",
    "Его пальцы разжались.": "His fingers unclenched.",
    "...тебе они больше не нужны.": "...you don't need these anymore.",
    "Наушники упали на бетонный пол. Маркус, не переставая улыбаться, наступил на них дорогим ботинком и с хрустом провернул ногу.": "The earphones hit the concrete floor. Marcus, still smiling, stepped on them with his expensive shoe and twisted his foot with a crunch.",
    "Тихий хруст пластика прозвучал для Неон как выстрел. Музыка умерла. Щит сломан. В её голову хлынул Шум.": "The quiet crunch of plastic sounded like a gunshot to Neon. The music died. Out goes the shield. The Noise flooded into her head.",
    "Упс. Неловко вышло. Как и вся твоя карьера, Синяя ворона.": "Oops. That was awkward. Like your whole career, Blue sheep.",
    "Синяя ворона.": "Blue sheep.",
    "Это слово. Это дурацкое слово...": "That word. That stupid word...",
    "Это презрение.": "That contempt.",
    "Это было не про карьеру.": "It wasn't about the career.",
    "Это было про нее саму.": "It was about her.",
    "Это был голос из прошлого.": "It was a voice from the past.",
    "Голос завуча. Голос опекунши. Голос тех, кто всегда говорил ей, что она 'не такая'": "The voice of the principal. The voice of her guardian. The voice of those who always told her she wasn't 'like the rest'.",
    "Ледяное спокойствие треснуло. И из-под него вырвался раскаленный поток чистой, испепеляющей ярости.": "The icy calm cracked. And from beneath it burst a white-hot stream of pure, incinerating rage.",
    "Она остановилась. Ее взгляд, до этого холодный, загорелся безумным огнем.": "She stopped. Her gaze, previously cold, ignited with an insane fire.",
    "Кровь ударила в голову. Ярость, слепая и испепеляющая, затопила сознание.": "Blood rushed to her head. A blind, incinerating rage flooded her consciousness.",
    "Она посмотрела на Маркуса уже не как на коллегу-предателя, а как на воплощение всего того, что ее мучило годами.": "She looked at Marcus not anymore as a traitor-colleague, but as the embodiment of everything that had tormented her for years.",
    "Ее взгляд упал на тяжелые металлические стулья вдоль... чего-то...": "Her gaze fell on the heavy metal chairs lining... something...",
    "Неон уже не понимает где она сама находится. Она видит только красный цвет вокруг себя и слышит только бешено колотящееся сердце в ушах.": "Neon doesn't even realize where she is. She only sees the color red around her and hears only the frantic pounding of her heart in her ears.",
    "А стулья, эти тяжелые металлические стулья, кажутся ей единственным оружием в этом мире, способным нанести удар по самому сердцу ее мучителя.": "And the chairs, those heavy metal chairs, seem to her the only weapon in this world capable of striking the very heart of her tormentor.",
    "{=whisper} Заткнись...": "{=whisper} Shut up...",
    "Что? Не расслышал. Говори громче.": "What? Didn't catch that. Speak up.",
    "Заткнись... ЗАТКНИСЬ. ПРОСТО ЗАТКНИСЬ!": "Shut up... SHUT UP. JUST SHUT UP!",
    "Я УСТАЛА. УСТАЛА БЫТЬ ДЛЯ ВСЕХ ПУСТЫМ МЕСТОМ!": "I'M TIRED. TIRED OF BEING NOTHING TO EVERYONE!",
    "Мне... МНЕ НИКОГДА БОЛЬШЕ НЕ БУДУТ УКАЗЫВАТЬ КАКАЯ Я!": "I will... I WILL NEVER AGAIN BE TOLD WHO I AM!",
    "Алекс, увидев безумие в глазах подруги, бросилась к ней.": "Alex, seeing the madness in her friend's eyes, rushed towards her.",
    "Неон... Стой! Не делай глупостей!": "Neon... Stop! Don't do anything stupid!",
    "Она схватила Неон за запястье, пытаясь удержать руку со стулом.": "She grabbed Neon by the wrist, trying to hold back the arm holding the chair.",
    "ТРЕСК!": "CRACK!",
    "Это был удар током.": "It was an electric shock.",
    "Алекс вскрикнула от боли, ее пальцы разжались сами собой. Она отшатнулась, прижимая обожженную ладонь к груди.": "Alex cried out in pain, her fingers unclenched automatically. She recoiled, clutching her burned palm to her chest.",
    "Ай!.. Неон?!": "Ow!.. Neon?!",
    "Неон даже не заметила этого. Она не почувствовала удара.": "Neon didn't even notice. She didn't feel the shock.",
    "Энергия внутри неё больше не искала выхода. Она искала цель. И целью был Маркус.": "The energy inside her was no longer looking for an outlet. It was looking for a target. And the target was Marcus.",
    "Она схватилась за спинку стула.": "She grabbed the back of the chair.",
    "Он казался невероятно тяжелым, но ее ярость давала ей силы, которых она в себе не подозревала.": "It felt incredibly heavy, but her rage gave her strength she hadn't suspected she possessed.",
    "С криком, вырвавшимся из глубины души, она оторвала стул от пола.": "With a scream torn from the depths of her soul, she lifted the chair off the floor.",
    "Ты... Ты что, совсем рехнулась?! Положи стул!": "Are... are you out of your mind?! Put the chair down!",
    "Неон замахнулась, а её синие волосы светились как пламя...": "Neon swung, her blue hair glowing like flames..."
  },
  
  r'f:\RenPyDevelopment\Projects\DoctorNeonPrototype\game\tl\english_us\game-scripts\chapters\chapter1\8-attack-scene.rpy': {
    "В глазах Неон не было ничего, кроме слепой, испепеляющей ярости. Ее лицо исказилось, превратившись в маску безумия.": "There was nothing in Neon's eyes but blind, incinerating rage. Her face contorted into a mask of madness.",
    "Синие волосы, казалось, потрескивали от статического электричества.": "Her blue hair seemed to crackle with static electricity.",
    "Маркус, увидев это преображение, попытался отступить, но ноги его не слушались. Он споткнулся и неуклюже попятился назад, его глаза расширились от первобытного ужаса.": "Marcus, seeing this transformation, tried to back away, but his legs wouldn't obey. He tripped and stumbled backwards clumsily, his eyes wide with primal terror.",
    "Н-неон... П-пожалуйста... Стой-стой-стой! Я... Да! Я все исправлю!": "N-neon... P-please... Wait-wait-wait! I... Yes! I'll fix everything!",
    "Вышло недоразумение! Я... это была шутка! Хаха! Да ладно тебе, Неон!": "It was a misunderstanding! I... it was just a joke! Haha! Come on, Neon!",
    "Но слова уже не имели значения. Неон издала низкий, гортанный рык, больше похожий на звериный, чем на человеческий.": "But the words no longer mattered. Neon let out a low, guttural growl, sounding more animalistic than human.",
    "Она занесла тяжелый металлический стул над головой.": "She raised the heavy metal chair above her head.",
    "Первый удар – яростный, но немного неточный из-за слепящей злости – пришелся не по плечу, как она целилась, а соскользнул, оглушительно ударив по стене рядом с головой Маркуса.": "The first blow – furious but slightly inaccurate due to blinding rage – missed the shoulder she aimed for and glanced off, crashing deafeningly into the wall next to Marcus's head.",
    "От стены отлетели куски штукатурки.": "Chunks of plaster flew from the wall.",
    "Маркус вскрикнул от страха и отшатнулся еще сильнее, теряя равновесие.": "Marcus shrieked into fear and scrambled backwards even harder, losing his balance.",
    "Он повалился на спину, пытается отползти, выставив свои руки перед собой в жалкой попытке защититься.": "He fell on his back, trying to crawl away, throwing his hands up in a pathetic attempt to protect himself.",
    "Неон, не останавливаясь ни на секунду, снова подняла стул.": "Neon, without stopping for a second, raised the chair again.",
    "Теперь ее движения были более точными, холодными, почти расчетливыми, несмотря на бушующую внутри ярость.": "Now her movements were more precise, cold, almost calculated, despite the rage raging inside.",
    "Она видела перед собой не человека, а символ всех своих страданий.": "She saw not a person before her, but a symbol of all her suffering.",
    "Второй удар. Тяжелый, глухой. Он обрушился на спину Маркуса, когда тот пытался перевернуться и встать.": "The second blow. Heavy, muffled. It reigned down on Marcus's back as he tried to roll over and get up.",
    "Раздался ужасающий хруст, и Маркус захлебнулся криком.": "There was a horrifying crunch, and Marcus choked on a scream.",
    "Он лежал на полу, лицом вниз, его руки были раскинуты. Он перестал двигаться, только тихо хрипел.": "He lay on the floor, face down, arms splayed out. He stopped moving, only letting out quiet wheezes.",
    "Алекс, прикрывая рот рукой, чтобы не закричать, смотрела на это с ужасом.": "Alex, covering her mouth with her hand to keep from screaming, watched in horror.",
    "Она узнавала этот взгляд Неон – такой же был у нее в те моменты, когда она рассказывала о своих самых мрачных снах или о чувстве преследования.": "She recognized that look from Neon – the same look she had when she used to talk about her darkest dreams or the feeling of being hunted.",
    "Но Неон еще не закончила. Ее грудь тяжело вздымалась.": "But Neon still wasn't done. Her chest moved heavily.",
    "Она обошла распростертое тело Маркуса, нависая над ним, как хищник над добычей. Стул все еще был в ее руках.": "She walked around Marcus's spread-eagled body, looming over him like a predator over prey. The chair was still in her hands.",
    "Она медленно подняла его в третий раз, целясь в голову.": "She slowly raised it a third time, aiming at his head.",
    "В этот момент, за мгновение до удара, лицо Маркуса, искаженное болью и страхом, на секунду прояснилось.": "At that moment, a split second before the strike, Marcus's face, contorted with pain and fear, cleared for a second.",
    "В его глазах мелькнуло что-то похожее на понимание... или смирение?": "Something akin to understanding... or resignation flashed in his eyes?",
    "Неон начала замахиваться для третьего удара, но она пошатнулась, увидев лицо Маркуса. На секунду она вернулась в чувства, потеряв равновесие.": "Neon began her swing for the third blow, but staggered when seeing Marcus's face. For a second she came back to her senses, losing her balance.",
    "Неон стояла над ним, тяжело дыша. Стул со стуком выпал из ее ослабевших рук за её спину.": "Neon stood over him, breathing heavily. The chair tumbled from her weakened hands, clattering behind her.",
    "Красная пелена ярости медленно начала спадать с ее глаз, уступая место холодному ужасу от содеянного.": "The red haze of rage slowly faded from her eyes, giving way to an icy dread of what she had done.",
    "В коридоре повисла оглушительная тишина, прерываясь дыханием Неон и тихими всхлипами Алекс, которая все еще сидела у стены.": "A deafening silence hung in the corridor, interrupted only by Neon's breathing and quiet sobs from Alex, who was still slumped against the wall.",
    "И тут, как будто издалека, донесся голос Ханса:": "And then, as if from afar, Hans's voice reached them:",
    "Эй! Я слышу грохот! Что у вас там происходит?!": "Hey! I hear a ruckus! What is going on over there?!"
  },

  r'f:\RenPyDevelopment\Projects\DoctorNeonPrototype\game\tl\english_us\game-scripts\chapters\chapter1\9-escape.rpy': {
    "Я смотрела на Маркуса, скрючившегося на полу, на свои дрожащие руки. В ушах звенело. Ярость ушла, оставив после себя ледяной ужас и тошнотворную пустоту.": "I looked at Marcus, crumpled on the floor, at my trembling hands. My ears were ringing. The rage had receded, leaving behind a chilling horror and a nauseating emptiness.",
    "Голос Ханса, кричащий из-за двери, становился все громче. Раздался лязг ключей в замке двери, ведущей на лестничную клетку.": "Hans's voice, shouting from behind the door, grew louder. A clatter of keys resounded from the lock of the door leading to the stairwell.",
    "Алекс вскочила на ноги. В ее глазах не было ни осуждения, ни страха. Только решимость.": "Alex sprang to her feet. There was no condemnation, no fear in her eyes. Only resolve.",
    "Неон! Очнись! Мы должны бежать! Сейчас же!": "Neon! Snap out of it! We have to run! Right now!",
    "Её слова с трудом пробивались сквозь вату в моих ушах. Бежать? Куда? Зачем? Я только что сломала человеку жизнь.": "Her words barely reached me through the cotton in my ears. Run? Where? Why? I just ruined someone's life.",
    "Я... я его... Алекс...": "I... I... Alex...",
    "Потом! Думать будем потом! Если тебя здесь найдут, тебе конец! Бежим!": "Later! We'll think about it later! If they find you here, you're done for! Run!",
    "Её теплая рука схватила мою ледяную ладонь. Этот контраст выдернул меня из оцепенения. Я позволила утащить себя за ней.": "Her warm hand grabbed my icy palm. The contrast pulled me out of my stupor. I let her drag me along.",
    "Какого черта?! Охрану на Уровень 1! И врача! Немедленно!": "What the hell?! Security to Level 1! And a medic! Immediately!",
    "Крик Ханса за спиной подхлестнул нас, как удар хлыста. Мы свернули к пожарному выходу.": "Hans's shout behind us whipped us like a lash. We turned towards the fire escape.",
    "Мы вырвались на узкую, тускло освещенную бетонную лестницу.": "We burst into a narrow, dimly lit concrete stairwell.",
    "Сверху уже доносился топот тяжелых ботинок службы безопасности. Они спускались за нами.": "The stamping of heavy security boots could already be heard from above. They were coming down after us.",
    "Мы бежали вниз, перепрыгивая через ступеньки. Мое сердце колотилось где-то в горле.": "We ran down, skipping steps. My heart was pounding somewhere in my throat.",
    "Парковка! Нам нужна парковка Р2! Моя карточка откроет нижний шлюз!": "The parking lot! We need parking level P2! My card will unlock the lower security door!",
    "Моя машина... там...": "My car's... there...",
    "Мы сбежали на самый нижний, технический уровень. Холодный, сырой коридор с гудящими трубами.": "We ran down to the very lowest, technical level. A cold, damp corridor with humming pipes.",
    "Впереди, в конце короткого коридора, виднелась тяжелая металлическая дверь с красной надписью 'EXIT - P2'.": "Ahead, at the end of the short corridor, stood a heavy metal door with a red 'EXIT - P2' sign.",
    "Но как только мы повернули за угол, из бокового прохода нам навстречу выскочили двое охранников.": "But as soon as we turned the corner, two security guards leapt out of a side passage right toward us.",
    "Стоять! Руки на стену!": "Freeze! Hands on the wall!",
    "Они преградили путь к двери.": "They blocked the way to the door.",
    "Я оглянулась. Сзади, с лестницы, которую мы только что покинули, уже выбегали еще трое.": "I looked back. From the stairwell we just left, three more were already rushing out.",
    "Тупик.": "Dead end.",
    "Мы оказались зажаты в крошечном бетонном кармане. Охранники спереди, охранники сзади. А спасительная дверь на парковку — всего в трех метрах, сбоку от нас.": "We were trapped in a tiny concrete pocket. Guards ahead, guards behind. The saving door to the parking lot — just three meters to our side.",
    "{=thoughts}Это конец. Ловушка захлопнулась.{/thoughts}": "{=thoughts}This is the end. The trap has sprung.{/thoughts}",
    "Я отступила к стене, готовясь сдаться.": "I backed against the wall, preparing to surrender.",
    "Но Алекс... Алекс не собиралась сдаваться.": "But Alex... Alex wasn't going down without a fight.",
    "Она прижала меня к стене, закрывая собой. Её лицо оказалось в сантиметре от моего.": "She pinned me to the wall, shielding me. Her face was an inch away from mine.",
    "Она тяжело дышала, её светлые кудри растрепались. Но в этот момент паники она вдруг... улыбнулась. Той самой, своей теплой, немного ехидной улыбкой.": "She was breathing heavily, her light curls disheveled. But in this moment of panic she suddenly... smiled. With that same warm, slightly mischievous smile of hers.",
    "{=whisper}Слушай меня внимательно, гений.{/whisper}": "{=whisper}Listen to me closely, genius.{/whisper}",
    "{=whisper}Алекс, нет... их слишком много...{/whisper}": "{=whisper}Alex, no... there's too many of them...{/whisper}",
    "Она взяла мое лицо в свои ладони. Её руки были такими горячими.": "She cradled my face in her hands. Her hands were burning hot.",
    "Она посмотрела мне прямо в глаза, стирая весь окружающий шум.": "She looked straight into my eyes, erasing all the surrounding noise.",
    "{=whisper}Там, за дверью — твоя машина.": "{=whisper}Out there, past the door, is your car.",
    "{=whisper}Ты не можешь здесь закончить. У тебя звезды, забыла?": "{=whisper}You can't end all of it here. You have stars to observe, remember?",
    "{=whisper}Алекс... что ты задумала? Я тебя не брошу! Я обещала!{/whisper}": "{=whisper}Alex... what are you doing? I'm not leaving you! I promised!{/whisper}",
    "Улыбка Алекс дрогнула, в глазах блеснули слезы, но она упрямо мотнула головой.": "Alex's smile faltered, tears glistening in her eyes, but she stubbornly shook her head.",
    "{=whisper}Я знаю. Поэтому я бросаю тебя первая.": "{=whisper}I know. That's why I'm leaving you first.",
    "{=whisper}Я... я люблю тебя, Неон. И я хочу, чтобы ты была в безопасности.": "{=whisper}I... I love you, Neon. And I want you to be safe.",
    "{=whisper}Найди своих пришельцев, Неон. И... не забывай нормально пить кофе, окей?": "{=whisper}Find your aliens, Neon. And... don't forget to drink your coffee right, okay?",
    "Она приложила свой бейдж к сканеру двери.": "She pressed her badge against the door scanner.",
    "Дверь на парковку с тяжелым щелчком приоткрылась.": "The parking lot door unsealed with a heavy click.",
    "А ТЕПЕРЬ БЕГИ!": "NOW RUN!",
    "С невероятной силой она толкнула меня в проем двери. Я влетела в полумрак парковки, споткнувшись и упав на колени.": "With an unbelievable force she shoved me into the doorway. I flew into the gloom of the parking lot, stumbling and falling to my knees.",
    "Обернувшись, я увидела, как Алекс с криком бросилась на охранников, сбивая их с ног, создавая хаос.": "Looking back, I saw Alex throw herself screaming at the guards, knocking them off their feet, creating chaos.",
    "Тяжелая дверь на доводчике захлопнулась, отрезая меня от неё.": "The heavy, self-closing door slammed shut, cutting me off from her.",
    "Я бросилась к небольшому армированному стеклу в двери.": "I rushed over to the small reinforced glass panel in the door.",
    "Там, по ту сторону, они вытягивали её с двери. Она отбивалась, держась за ручку, кричала, давая мне драгоценные секунды.": "There, on the other side, they were peeling her off the door. She fought back, clutching the handle, screaming, giving me precious seconds.",
    "Она посмотрела на дверь. На меня. И одними губами прошептала: 'Беги'.": "She looked at the door. At me. And whispered with just her lips: 'Run'.",
    "{=thoughts}Я... я оставила её там.{/thoughts}": "{=thoughts}I... I left her there.{/thoughts}",
    "Чувство вины, черное и липкое, мгновенно затопило душу. Но животный инстинкт самосохранения заставил меня подчиниться её последней просьбе.": "Guilt — dark, viscous — instantly flooded my soul. But an animalistic instinct for self-preservation made me yield to her final wish.",
    "Я развернулась и побежала в гулкую темноту подземной парковки.": "I turned back around and ran into the echoing darkness of the underground parking lot.",
    "Моя старенькая красная Mazda 323 стояла в дальнем углу.": "My ragged red Mazda 323 sat in the far corner.",
    "Дрожащими руками я достала ключи.": "With trembling hands I fumbled for my keys.",
    "Я ввалилась в салон. Запах моего парфюма и старых книг. Безопасность.": "I fell into the cabin. The smell of my perfume and old books. Safe.",
    "Но дверь из комплекса уже открывалась. Охрана прорвалась.": "But the door from the complex was opening. Security poured out.",
    "Ключ в замок. Стартер натужно взвизгнул, и двигатель ожил.": "Key into the ignition. The starter squealed straining, and the engine rattled to life.",
    "Прости меня, Алекс... Прости...": "I'm sorry, Alex... I'm so sorry...",
    "Я вдавила педаль газа в пол. Машина с визгом сорвалась с места.": "I stomped the gas pedal. The car screechingly ripped out of place.",
    "Я вылетела по винтовому пандусу на поверхность.": "I shot up the spiral ramp toward the surface.",
    "Главный КПП комплекса 'Гелиос' был впереди. Шлагбаум опущен.": "The Helios Complex's main security checkpoint was ahead. Gate lowered.",
    "Я не стала тормозить. Я просто вцепилась в руль.": "I didn't try to brake. I just gripped the steering wheel.",
    "Удар. Треск ломающегося пластика и металла.": "Impact. The crunching crackle of breaking plastic and tearing metal.",
    "Я протаранила шлагбаум и вырвалась на горный серпантин, ведущий вниз, к главному шоссе.": "I crashed through the barrier and burst out onto the mountain serpentines leading downward to the main highway.",
    "Но за мной уже гнались. В зеркале заднего вида появились слепящие фары корпоративного внедорожника.": "But they were giving chase. The blinding headlights of a corporate SUV appeared in the rearview.",
    "Хлопки. Они стреляли по колесам.": "Pops. They were firing at my tires.",
    "Дорога была мокрой. Скорость слишком высокой.": "The road was wet. My speed way too high.",
    "Очередной крутой поворот. Машину занесло. Руль стал легким и бесполезным.": "Another sharp turn. The car skids. The steering wheel becomes light and useless.",
    "Мы пробили хлипкое ограждение.": "We broke through the flimsy guardrail.",
    "Чувство невесомости. Моя Mazda слетела с горной дороги вниз, по крутому лесистому склону, проламывая кусты и мелкие деревья.": "Sense of weightlessness. My Mazda tumbled off the mountain road to the steep wooded slope below, crashing through bushes and small trees.",
    "Удары. Звон стекла. Мир завертелся в кровавой карусели.": "Blows. Ringing glass. The world spun in a bloody carousel.",
    "А затем — тяжелый, зубодробительный удар.": "And then — a heavy, bone-crushing impact.",
    "Моя машина вылетела из оврага и с лязгом рухнула прямо на полотно нижнего скоростного шоссе.": "My car flew out of the ravine and clattered directly onto the pavement of a lower expressway.",
    "Я висела на ремнях, оглушенная. Кровь заливала глаза.": "I hung by my seat belts, deafened. Blood flooding my eyes.",
    "Я с трудом повернула голову.": "I agonizingly moved my head to my side.",
    "Прямо на меня, из ночного мрака, неслась многотонная фура.": "A multi-ton semi sprinted from out of the night's darkness directly toward me.",
    "Водитель жал на гудок, звук которого разрывал барабанные перепонки. Тормозить было поздно.": "The driver pressed his horn, tearing at my eardrums. It was too late to brake.",
    "Два огромных, безжалостных глаза-прожектора впились в меня, парализуя волю. Они слепили. Они были слишком яркими.": "Two huge, merciful spotlights stared directly at me, paralyzing my will. Brightening. They were too bright.",
    "{=thoughts}Яркие... как её улыбка...{/thoughts}": "{=thoughts}Bright... like her smile...{/thoughts}",
    "{=thoughts}Алекс...{/thoughts}": "{=thoughts}Alex...{/thoughts}",
    "Время превратилось в вязкую смолу.": "Time turned into thick resin.",
    "Я смотрела на этот надвигающийся свет, и в моей груди поднималась не паника, а абсолютное, ледяное отторжение.": "I looked at the encroaching light, and what swelled in my chest was not panic, but an absolute frozen rejection.",
    "{=thoughts}Я бы хотела повернуть время вспять...{/thoughts}": "{=thoughts}I wish I could turn back time...{/thoughts}",
    "{=thoughts}Снова увидеть Алекс... Яркую, как этот прожектор...{/thoughts}": "{=thoughts}To see Alex again... Bright, just like this spotlight...{/thoughts}",
    "{=thoughts}Я не хочу, чтобы этот день существовал.{/thoughts}": "{=thoughts}I don't want this day to exist.{/thoughts}",
    "Я хочу... его... отменить...": "I want... to cancel... it...",
    "Вспышка.": "Flash.",
    "И мгновенная, глухая, неестественная тишина. Гудок фуры просто... исчез.": "And instant, deafening, unnatural silence. The semi's horn simply... vanished.",
    "А затем...": "And then...",
    "Это был не звук сминаемой легковушки.": "It wasn't the sound of an agonizing car wreck.",
    "Раздался чудовищный, оглушительный скрежет рвущегося металла, звон рассыпающегося стекла и взрывающихся шин. Земля подо мной содрогнулась так, словно началось землетрясение.": "A monstrous, deafening scrape of tearing metal, ringing of shattering glass and popping tires tore out. The ground under me shook like an earthquake.",
    "Меня обдало волной раскаленного воздуха и осколками стекла.": "I was showered by a wave of red-hot air and glass shards.",
    "Многотонный левиафан врезался во что-то прямо передо мной... и смялся, как фольга.": "A multi-ton leviathan crashed into something directly in front of me... and crumbled like tinfoil.",
    "Но удара по моей машине так и не последовало.": "But an impact never affected my car.",
    "А затем сознание, не выдержав этого невозможного, сюрреалистичного парадокса, милосердно провалился в густую, спасительную тьму.": "And then my mind, giving up on this impossible, surreal paradox, mercifully sank into dense, relieving darkness."
  }
}

for file_path, translations in files_and_translations.items():
    with open(file_path, 'r', encoding='utf-8') as f:
        text = f.read()

    for rus, eng in translations.items():
        escaped_rus = re.escape(rus)
        pattern_proper = r'(#\s*.+?"' + escaped_rus + r'")\n(\s*(?:\"[^\"]+\"|\w+(?:\s+\w+)*)\s+)""'
        text = re.sub(pattern_proper, r'\1\n\2"' + eng.replace('\\', '\\\\').replace('"', '\\"') + r'"', text)

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(text)

print("Updated translation for remaining chapter 1 files.")
